In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [14]:
df = pd.read_csv(r'C:\Users\mk929\Downloads\Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [33]:
df["Species"] = df["Species"].str.replace("Iris-", "", regex=False)

In [43]:
df.head(80)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
0    1            5.1           3.5            1.4           0.2      setosa
1    2            4.9           3.0            1.4           0.2      setosa
2    3            4.7           3.2            1.3           0.2      setosa
3    4            4.6           3.1            1.5           0.2      setosa
4    5            5.0           3.6            1.4           0.2      setosa
..  ..            ...           ...            ...           ...         ...
75  76            6.6           3.0            4.4           1.4  versicolor
76  77            6.8           2.8            4.8           1.4  versicolor
77  78            6.7           3.0            5.0           1.7  versicolor
78  79            6.0           2.9            4.5           1.5  versicolor
79  80            5.7           2.6            3.5           1.0  versicolor

[80 rows x 6 columns]

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le=LabelEncoder()

In [60]:
df['Species_en'] = le.fit_transform(df['Species'])

In [62]:
df = df.drop('Species', axis=1)

In [64]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species_en
0   1            5.1           3.5            1.4           0.2           0
1   2            4.9           3.0            1.4           0.2           0
2   3            4.7           3.2            1.3           0.2           0
3   4            4.6           3.1            1.5           0.2           0
4   5            5.0           3.6            1.4           0.2           0

In [44]:
df.shape

(150, 6)

In [65]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species_en       0
dtype: int64

In [66]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [69]:
x = df.drop(columns=['Species_en', 'Id'])
y = df['Species_en']

In [70]:
print(x)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [71]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species_en, Length: 150, dtype: int64

In [72]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [73]:
print(x.shape,x_train.shape,x_test.shape)

(150, 4) (120, 4) (30, 4)

In [74]:
model = LogisticRegression()

In [75]:
model.fit(x_train,y_train)

LogisticRegression()

In [76]:
y_pred = model.predict(x_test)

In [77]:
accuracy = accuracy_score(y_test,y_pred)

In [78]:
print(accuracy)

1.0

In [79]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

e:\Iris Flower Classification\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [80]:
import pickle

In [81]:
with open("iris_dataset.pkl",'wb') as f:
    pickle.dump(model,f)